// Generated by CoffeeScript 2.5.1
(function() {
  // (params) -> body
  var greet, result, sayHello, square, squares;

  sayHello = function(name) {
    return "Hello there, " + name;
  };

  greet = (name) => {
    return "Hello there, " + name;
  };

  console.log(sayHello("Joanna"));

  console.log(greet("Joanna"));

  square = function(x) {
    return Math.pow(x, 2);
  };

  squares = [1, 2, 3, 4, 5].map(square); // pass function by name

  result = (function(x) {
    return x * 5;
  })(16); // call anonymous function

  console.log(square(4));

  console.log(squares());

  console.log(result());

}).call(this);
