// Generated by CoffeeScript 2.5.1
(function() {
  var a, b, c, i, j, k, ref, ref1;

  for (c = i = 1; i <= 40; c = ++i) {
    for (b = j = 1, ref = c; (1 <= ref ? j < ref : j > ref); b = 1 <= ref ? ++j : --j) {
      for (a = k = 1, ref1 = b; (1 <= ref1 ? k < ref1 : k > ref1); a = 1 <= ref1 ? ++k : --k) {
        if (a * a + b * b === c * c) {
          console.log(`${a}, ${b}, ${c}`);
        }
      }
    }
  }

}).call(this);
